"""empty message

Revision ID: 4f2835748d50
Revises: 
Create Date: 2025-09-16 14:55:36.874126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2835748d50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=60), nullable=False),
    sa.Column('eye_color', sa.String(length=60), nullable=True),
    sa.Column('birth_year', sa.String(length=20), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('people_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'people_id'),
    sa.UniqueConstraint('user_id', 'people_id', name='uq_user_people')
    )
    with op.batch_alter_table('people_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_favorites_people_id'), ['people_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('planet_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'planet_id'),
    sa.UniqueConstraint('user_id', 'planet_id', name='uq_user_planet')
    )
    with op.batch_alter_table('planet_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planet_favorites_planet_id'), ['planet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planet_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('vehicle_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'vehicle_id'),
    sa.UniqueConstraint('user_id', 'vehicle_id', name='uq_user_vehicle')
    )
    with op.batch_alter_table('vehicle_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_favorites_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_favorites_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_favorites_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_favorites_user_id'))

    op.drop_table('vehicle_favorites')
    with op.batch_alter_table('planet_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planet_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_planet_favorites_planet_id'))

    op.drop_table('planet_favorites')
    with op.batch_alter_table('people_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_people_favorites_people_id'))

    op.drop_table('people_favorites')
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
