"""empty message

Revision ID: 5a420cc482e4
Revises: 0763d677d453
Create Date: 2025-09-12 15:07:09.953652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a420cc482e4'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('people_favorites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_favorites')
    op.drop_table('people')
    # ### end Alembic commands ###
