"""empty message

Revision ID: 60e20872f167
Revises: 4f2835748d50
Create Date: 2025-09-16 15:13:21.529313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e20872f167'
down_revision = '4f2835748d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_people', ['user_id', 'people_id'])

    with op.batch_alter_table('planet_favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_planet', ['user_id', 'planet_id'])

    with op.batch_alter_table('vehicle_favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_vehicle', ['user_id', 'vehicle_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_favorites', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_vehicle', type_='unique')

    with op.batch_alter_table('planet_favorites', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_planet', type_='unique')

    with op.batch_alter_table('people_favorites', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_people', type_='unique')

    # ### end Alembic commands ###
